### ISSUE TITLE
这个怎么用

### ISSUE THREAD

**Issue by NoMathExpectation** [DreamVoid/Link2QQ#1]
这个怎么用啊，不写个简介吗

**Comment by DreamVoid** [comment]
这里：https://www.mcbbs.net/thread-1234632-1-1.html
本来想写个自述文件的，忘了

**Comment by NoMathExpectation** [comment]
不是，我是说开发者怎么用
有javadocs吗？

**Comment by DreamVoid** [comment]
> 不是，我是说开发者怎么用
> 有javadocs吗？

这个是给玩家用的，不是给开发者用的
开发者要调用MiraiMC的绑定数据直接用```MiraiMC```的类就行了：https://docs.miraimc.dreamvoid.ml/me/dreamvoid/miraimc/api/MiraiMC.html
